spring.application.name=restauranteSpring

spring.datasource.url="jdbc:postgresql://localhost:5432/restaurante"
spring.datasource.username="postgres"
spring.datasource.password="0803"

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

